import type { Metadata } from "next";

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "FundusAI Marketplace",
  description: "Generated by create next app",
};

export default function MarketPlaceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <div className="flex min-h-screen w-full items-center justify-center">
        {children}
      </div>
    </div>
  );
}
