import type { Metadata } from "next";

import { MainNav } from "@/components/admin ui/MainNav";
import { UserNav } from "@/components/UserNav";

export const metadata: Metadata = {
  title: "FundusAI Marketplace Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen w-full">
      <div className="hidden flex-col md:flex">
        <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <MainNav className="mx-6" />
            <div className="items-right ml-auto flex space-x-4">
              <UserNav />
            </div>
          </div>
        </div>
        {children}
      </div>
    </div>
  );
}
